### ISSUE TITLE
Add progress bar for file upload

### ISSUE THREAD

**Issue by ahmedashfaq027** [ahmedashfaq027/file-share#1]
During File Upload, show progress bar/spinner, so user will know the progress of file upload.

**Comment by saif-malik-01** [comment]
I want to work on this, please assign it to me.

**Comment by ahmedashfaq027** [comment]
@saif-malik-01, I have assigned it to you!

**Comment by ahmedashfaq027** [comment]
@saif-malik-01, What's the status? 
Are you working on this? or should I unassign you from this issue?

**Comment by saif-malik-01** [comment]
I'm working, will make a pr tommorow .

**Comment by ahmedashfaq027** [comment]
Thanks for acknowledging @saif-malik-01
